os:
  editPreset: 'vscode'

gui:
  nerdFontsVersion: "3"

  showCommandLog: false 
  showFileTree: true
  showIcons: true

git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers --hyperlinks
